[build]
  node_version = "20"

[phases.setup]
  nixPkgs = [
    "libnss", 
    "gtk3", 
    "glibc", 
    "chromium", 
    "atk", 
    "cups", 
    "alsa-lib", 
    "pango", 
    "libxshmfence", 
    "libx11", 
    "mesa", 
    "mesa_drivers",
    "libxcomposite", 
    "libxdamage", 
    "libxrandr"
  ]