[build]
  node_version = "20"

[phases.setup]
  nixPkgs = [
    "nss",
    "gtk3",
    "glibc",
    "chromium",
    "atk",
    "cups",
    "alsa-lib",
    "pango",
    "mesa",
    "mesa_drivers",
    "xorg.libX11",
    "xorg.libXcomposite",
    "xorg.libXdamage",
    "xorg.libXrandr",
    "xorg.libXshmfence"  # ✅ Fixed
  ]