[build]
  node_version = "20"

[phases.setup]
  nixPkgs = [
    "nss",                # ✅ Fixed
    "gtk3",
    "glibc",
    "chromium",
    "atk",
    "cups",
    "alsa-lib",
    "pango",
    "libxshmfence",
    "mesa",
    "mesa_drivers",
    "xorg.libX11",        # ✅ Fixed
    "xorg.libXcomposite", # ✅ Fixed
    "xorg.libXdamage",    # ✅ Fixed
    "xorg.libXrandr"      # ✅ Fixed
  ]