name: Deploy Playwright API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Update to Node.js 16 (or other suitable version)

    - name: Install dependencies
      run: |
        npm install
        npm install playwright-extra puppeteer-extra-plugin-stealth # Ensure additional dependencies are installed

    - name: Build and start server
      run: |
        nohup npm start &  # Run the app in the background to ensure it doesn't block the workflow

    - name: Wait for server to start
      run: |
        sleep 15  # Wait for server to fully initialize

    - name: Verify server is running
      run: curl http://localhost:8080/api/health
